################################################################################
# Copyrights © 2021-2022 Fiserv, Inc. or its affiliates. 
# Fiserv is a trademark of Fiserv, Inc., 
# registered or used in the United States and foreign countries, 
# and may or may not be registered in your country.  
# All trademarks, service marks, 
# and trade names referenced in this 
# material are the property of their 
# respective owners. This work, including its contents 
# and programming, is confidential and its use 
# is strictly limited. This work is furnished only 
# for use by duly authorized licensees of Fiserv, Inc. 
# or its affiliates, and their designated agents 
# or employees responsible for installation or 
# operation of the products. Any other use, 
# duplication, or dissemination without the 
# prior written consent of Fiserv, Inc. 
# or its affiliates is strictly prohibited. 
# Except as specified by the agreement under 
# which the materials are furnished, Fiserv, Inc. 
# and its affiliates do not accept any liabilities 
# with respect to the information contained herein 
# and are not responsible for any direct, indirect, 
# special, consequential or exemplary damages 
# resulting from the use of this information. 
# No warranties, either express or implied, 
# are granted or extended by this work or 
# the delivery of this work
################################################################################
header:
  productName: BillPay
  productionDescription: Transform online billpay experiences through personalization, automation and unmatched connectivity with CheckFree Next. CheckFree Next positions financial institutions to be first in line for their accountholders' digital payments needs by offering intelligent suggestions and putting more automation into the bill pay process to simplify the bill pay experience.
  whoIsItFor:  Provide small businesses with a comprehensive bill pay solution.
getStarted: "docs/introduction/getting-started.md"
benefits:
  - title: Fast time to market
    description: Tap into flexible integrations with existing payment platforms to quickly deploy consumer bill pay solutions.
    icon: assets/images/timetomarket.jpg
  - title: Unmatched size/scale
    description: NOW® Network access and an expansive network of billers enables faster payments and offers the real-time capabilities that accountholders expect.
    icon: assets/images/unmatchedsize.jpg
  - title: Consumer-centric
    description: Simplify the bill payer's experience with automation that connects billers to consumer accounts.
    icon: assets/images/consumer.jpg
guides:
  - title: Important to know
    description: Formatting, dates, field encoding and resource modification.
    link: "docs/resourcesAndGuides/importantToKnow.md"
  - title: Response codes 
    description: Standard response codes indicate the success or failure of an API request.
    link: "docs/resourcesAndGuides/responseCodes.md"
  - title: Versioning/compatibility
    description: If a breaking change is required, a new version will be created.
    link: "docs/resourcesAndGuides/versioningAndBackwardsCompatibility.md" 
useCases:
  - title: Bill Payment
    subtitle:
    description: Accept bill payments for one or more businesses and submit the payments for processing to the Fiserv payments services.
    link: "docs/introduction/getting-started.md"
  - title: Bill Discovery
    subtitle:
    description: Finds bills automatically (based on credit reports and/or biller direct statements) without having to start from a blank slate. 
    link: "docs/introduction/getting-started.md"
