################################################################################
# Copyrights © 2021-2022 Fiserv, Inc. or its affiliates. 
# Fiserv is a trademark of Fiserv, Inc., 
# registered or used in the United States and foreign countries, 
# and may or may not be registered in your country.  
# All trademarks, service marks, 
# and trade names referenced in this 
# material are the property of their 
# respective owners. This work, including its contents 
# and programming, is confidential and its use 
# is strictly limited. This work is furnished only 
# for use by duly authorized licensees of Fiserv, Inc. 
# or its affiliates, and their designated agents 
# or employees responsible for installation or 
# operation of the products. Any other use, 
# duplication, or dissemination without the 
# prior written consent of Fiserv, Inc. 
# or its affiliates is strictly prohibited. 
# Except as specified by the agreement under 
# which the materials are furnished, Fiserv, Inc. 
# and its affiliates do not accept any liabilities 
# with respect to the information contained herein 
# and are not responsible for any direct, indirect, 
# special, consequential or exemplary damages 
# resulting from the use of this information. 
# No warranties, either express or implied, 
# are granted or extended by this work or 
# the delivery of this work
################################################################################
header:
  productName: BillPay
  productionDescription: Transform online billpay experiences through personalization, automation and unmatched connectivity with CheckFree Next. CheckFree Next positions financial institutions to be first in line for their accountholders' digital payments needs by offering intelligent suggestions and putting more automation into the bill pay process to simplify the bill pay experience.
  whoIsItFor:  Provide small businesses with a comprehensive bill pay solution.
getStarted: "docs/introduction/getting-started.md"
benefits:
  - title: Fast time to market
    description: Tap into flexible integrations with existing payment platforms to quickly deploy consumer bill pay solutions.
    icon: assets/images/timetomarket.jpg
  - title: Unmatched size/scale
    description: NOW® Network access and an expansive network of billers enables faster payments and offers real-time capabilities.
    icon: assets/images/unmatchedsize.jpg
  - title: Consumer-centric
    description: Simplify the bill payer's experience with automation that connects billers to consumer accounts.
    icon: assets/images/consumer.jpg
featuredFeatures:
  - title: Bill Discovery
    featured: true
    description: Find bills by using information from credit report and biller statements with the consumer’s consent and select to add payees conveniently.
    relatedDocs:
      - link: "docs/introduction/overview.md"
        title: Overview
    relatedAPIs:
      - type:
        path:
        title: 
  - title: Reminders
    featured: true
    description: Receive alerts for due bills without giving up paper.
    relatedDocs:
      - link: "docs/introduction/overview.md"
        title: Overview
    relatedAPIs:
      - type: 
        path:
        title: 
  - title: Automatic Transactions
    featured: true 
    description: Automate payments and never be late with a payment again.
    relatedDocs:
      - link: "docs/introduction/overview.md"
        title: Overview
    relatedAPIs:
      - type: 
        path:
        title:
guides:
  - title: Important to know
    description: Formatting, dates, field encoding and resource modification.
    link: "docs/resourcesAndGuides/importantToKnow.md"
  - title: Response codes 
    description: Standard response codes indicate success or failure of a request.
    link: "docs/resourcesAndGuides/responseCodes.md"
  - title: Versioning/compatibility
    description: If a breaking change is required, a new version will be created.
    link: "docs/resourcesAndGuides/versioningAndBackwardsCompatibility.md" 
